<?php
$urlPattern = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern) {
    if (!preg_match('/page/', $urlPattern))
        return $urlPattern . '/page/' . (int) $page;
    else
        return preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern);
};



if ($this->pageCount):
    ?>

    <div class="pagination pagination-centered">

        <ul>

            <?php if (isset($this->previous)): ?>

            <a class="testeli" href="<?php echo $formatUrl($this->previous); ?> ">«</a>

            <?php else: ?>

                <a class="testeli" href="#">«</a>

            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>

                <?php if ($page != $this->current): ?>

                        <a class="testeli" href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>

                <?php else: ?>

                        <a class="testeli" href="#"><?php echo $page; ?></a>

                <?php endif; ?>

            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>

                    <a class="testeli" href="<?php echo $formatUrl($this->next); ?>">»</a>

            <?php else: ?>

               <a class="testeli" href="#">»</a>

            <?php endif; ?>

        </ul>

    </div>

<?php endif; ?>